### ISSUE TITLE
[ERROR] [1727288517.959824922] [scan_matcher]: Lookup would require extrapolation into the future.  Requested time 1.750000 but the latest data is at time 1.700000, when looking up transform from frame [base_link] to frame [odom]

### ISSUE THREAD

**Issue by nishantomnipotent** [Wiktor-99/mobile_robots_playground#1]
When I change the world I get this error any ideas as to how to solve it

**Comment by Wiktor-99** [comment]
I've checked it and it seems that you need to add following line to the sdf world:

```xml
<plugin filename="RGLServerPluginManager" name="rgl::RGLServerPluginManager"/>
```
I believe that the lidar slam has problem when point cloud is missing.

Let me know if it works.
